### ISSUE TITLE
[1.14.4] Client crash on load - Exception caught during firing event: Cannot get config value without assigned Config object present

### ISSUE THREAD

**Issue by ProsperCraft** [Yamahari/I-Like-Wood#10]
Stacktrace
https://gist.github.com/ProsperCraft/a5c47142188d03bf9ece216629ab7fee

[latest.log](https://github.com/Yamahari/I-Like-Wood/files/3541458/latest.log)
[debug.log](https://github.com/Yamahari/I-Like-Wood/files/3541459/debug.log)

Server crashed too

[latest.log](https://github.com/Yamahari/I-Like-Wood/files/3541464/latest.log)
[debug.log](https://github.com/Yamahari/I-Like-Wood/files/3541465/debug.log)

**Comment by Yamahari** [comment]
seems to be an compat issue with another mod, I think I know how to fix though

**Comment by Yamahari** [comment]
should be fixed in ilikewood-1.14.4-1.1.0.2

**Comment by Yamahari** [comment]
nvm I skipped something

**Comment by Yamahari** [comment]
nvm i am dumb, should be fixed x)
