### ISSUE TITLE
Ladders vs. Trapdoors & Axes

### ISSUE THREAD

**Issue by ZeroLevels** [Yamahari/I-Like-Wood#12]
Trapdoors are climbable in 1.14 when placed above a ladder.  The mod variations of the ladders don't do this.  They also don't break faster when chopped with an axe.

**Comment by Yamahari** [comment]
fixed axes not mining ladders faster ( my axes included ), can't do anything about the climbing part though without making a PR to Forge to remove the hardcoded vanilla stuff
