### ISSUE TITLE
Missing registries after removing mod

### ISSUE THREAD

**Issue by Ackmard** [Yamahari/I-Like-Wood#13]
I get this every time i re-launch minecraft and try to play my world after removing your mod, any idea why and/or how to fix it? Thanks in advance

![image](https://user-images.githubusercontent.com/26508542/65018216-3f4ac380-d931-11e9-90e5-3ec5c3dae4f0.png)

**Comment by FinnT730** [comment]
Maybe it is because you removed the mod???
If you remove a mod, do you really expect the blocks to be in the world????

**Comment by JoJoDeveloping** [comment]
back up the world, click "Yes", and expect blocks from ilikewood to be air now.

**Comment by Ackmard** [comment]
Did you read the part where I said that it happens every time I re-launch Minecraft? Even if I click "Yes"
