### ISSUE TITLE
[1.14.4] Crash on load on dedicated server

### ISSUE THREAD

**Issue by ProsperCraft** [Yamahari/I-Like-Wood#9]
https://gist.github.com/ProsperCraft/2cff3e4e0e9bef2fc7a0a271c15735f7

ilikewood-1.14.4-1.1.0.0

**Comment by Yamahari** [comment]
What version of forge?

**Comment by ProsperCraft** [comment]
forge-1.14.4-28.0.55

**Comment by Yamahari** [comment]
https://github.com/Yamahari/I-Like-Wood/blob/4289b2cb323b6de7016096955b075bfa007f6613/src/main/java/yamahari/ilikewood/blocks/WoodenBedBlock.java#L22 found the issue, this.getColor() calls a client side method

**Comment by Yamahari** [comment]
should be fixed in ilikewood-1.14.4-1.1.0.1
